from __future__ import annotations
import base64
import json
import uuid
from typing import Any
from lxml import etree

W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"


def create_mendeley_sdt(
    citation_text: str,
    items: list[dict[str, Any]],
    instance_id: int | None = None,
) -> etree._Element:
    """Constructs a genuine Mendeley Cite v3 structured document tag (<w:sdt>)

    containing base64-encoded CSL-JSON reference data.
    """
    if instance_id is None:
        instance_id = int(uuid.uuid4().int % 1000000000)

    citation_uuid = str(uuid.uuid4())
    csl_items = []
    for item in items:
        item_uuid = item.get("id") or str(uuid.uuid5(uuid.NAMESPACE_DNS, f"mendeley.{item.get('title', '')}"))
        csl_items.append({
            "id": item_uuid,
            "itemData": {
                "id": item_uuid,
                "type": item.get("type", "article-journal"),
                "title": item.get("title", "Untitled"),
                "author": item.get("author", [{"family": "Author", "given": "A."}]),
                "issued": item.get("issued", {"date-parts": [[2024]]}),
                "container-title": item.get("journal", item.get("container-title", "")),
                "volume": str(item.get("volume", "")),
                "page": str(item.get("pages", item.get("page", ""))),
                "DOI": item.get("doi", ""),
                "PMID": item.get("pmid", ""),
            },
            "isTemporary": False,
        })

    payload = {
        "citationID": f"MENDELEY_CITATION_{citation_uuid}",
        "properties": {"noteIndex": 0},
        "isEdited": False,
        "manualOverride": {
            "isManuallyOverridden": False,
            "citeprocText": citation_text,
            "manualOverrideText": "",
        },
        "citationItems": csl_items,
    }

    raw_json = json.dumps(payload, ensure_ascii=False)
    b64_tag = "MENDELEY_CITATION_v3_" + base64.b64encode(raw_json.encode("utf-8")).decode("ascii")

    sdt = etree.Element(f"{{{W_NS}}}sdt", nsmap={"w": W_NS})
    sdtPr = etree.SubElement(sdt, f"{{{W_NS}}}sdtPr")
    etree.SubElement(sdtPr, f"{{{W_NS}}}tag", attrib={f"{{{W_NS}}}val": b64_tag})
    etree.SubElement(sdtPr, f"{{{W_NS}}}id", attrib={f"{{{W_NS}}}val": str(instance_id)})

    sdtContent = etree.SubElement(sdt, f"{{{W_NS}}}sdtContent")
    r = etree.SubElement(sdtContent, f"{{{W_NS}}}r")
    t = etree.SubElement(r, f"{{{W_NS}}}t")
    t.text = citation_text

    return sdt


def create_mendeley_bibliography_marker() -> etree._Element:
    """Creates a Mendeley Bibliography SDT marker at the end of the manuscript."""
    sdt = etree.Element(f"{{{W_NS}}}sdt", nsmap={"w": W_NS})
    sdtPr = etree.SubElement(sdt, f"{{{W_NS}}}sdtPr")
    etree.SubElement(sdtPr, f"{{{W_NS}}}tag", attrib={f"{{{W_NS}}}val": "MENDELEY_BIBLIOGRAPHY"})
    etree.SubElement(sdtPr, f"{{{W_NS}}}id", attrib={f"{{{W_NS}}}val": str(uuid.uuid4().int % 1000000000)})
    sdtContent = etree.SubElement(sdt, f"{{{W_NS}}}sdtContent")
    p = etree.SubElement(sdtContent, f"{{{W_NS}}}p")
    r = etree.SubElement(p, f"{{{W_NS}}}r")
    t = etree.SubElement(r, f"{{{W_NS}}}t")
    t.text = "Bibliography generated by Mendeley Cite"
    return sdt

